---
include:
  - board: nice_nano_v2
    shield: charybdis_left
    extra_modules: ./config
  - board: nice_nano_v2
    shield: charybdis_right
    extra_modules: ./config
  - board: nice_nano_v2
    shield: settings_reset
    extra_modules: ./config
